### ISSUE TITLE
manifest for kaixhin/cuda-torch:latest not found

### ISSUE THREAD

**Issue by deepakcrk** [bgshih/crnn#101]
I am getting following error while executing following command:
` sudo docker build -t crnn_docker .`

```
Sending build context to Docker daemon  304.6kB
Step 1/11 : FROM kaixhin/cuda-torch
manifest for kaixhin/cuda-torch:latest not found
```
How I can fix the same ?

**Comment by 00hello** [comment]
It's because there is no build tagged "latest" in dockerhub. -> https://hub.docker.com/r/kaixhin/cuda-torch/tags/

At least, not anymore. 

What I did was edit the Dockerfile and added  ":8.0" to the end of FROM kaixhin/cuda-torch

`FROM kaixhin/cuda-torch:8.0`

**Comment by YHCodes** [comment]
@00hello  thanks,  it works

**Comment by ashavish** [comment]
Just tried.. not working.. 
It already has FROM kaixhin/cuda-torch-deps:2-7.0
