### ISSUE TITLE
请问代码中到底有没有限制长度

### ISSUE THREAD

**Issue by Duum** [bgshih/crnn#12]
```
function loadAndResizeImage(imagePath)
    local img = Image.load(imagePath, 3, 'byte')
    img = Image.rgb2y(img)
    img = Image.scale(img, 100, 32)[1]
    return img
end

```
您好：
　　　在这个函数中图片被scale了定长定宽，貌似与论文中定宽不定长不符？

**Comment by bgshih** [comment]
@Duum You can use test with other image widths as well.

**Comment by sangramgupta** [comment]
@bgshih Hi, I wanted to change the image height and width so as to play and get the best results but I am able to change and make the program run when changing width but am not able to make the program work when I tweak image Height to other than 32. Please advise and suggest a way out. Thanks in advance.

**Comment by bgshih** [comment]
@sangramgupta Due to the network design, the height cannot be changed, only the width.

**Comment by xylcbd** [comment]
the width of image is variable in the paper , but this implemented use fixed image width , why ?
