### ISSUE TITLE
accuray: 0.000000

### ISSUE THREAD

**Issue by Aurora11111** [bgshih/crnn#128]

**Comment by Aurora11111** [comment]
my print is strange:
[24/25][432/432] Loss: 11.319855
Start val
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe6\xbd\xad\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe9\xbe\x88\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe6\xbf\x91\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe6\xba\xa7\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe6\xae\x96\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe7\x97\xa3\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe8\xa2\x88\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe6\xae\xbf\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe5\x87\x80\n'
b'\xe5\\\x9-0\xb1\nn' => b'\xe5\x90\xb1\n' , gt: b'\xe9\x9e\x8d\n'
Test loss: 11.234461, accuray: 0.000156

**Comment by Aurora11111** [comment]
Now ,it is change to :

Start val
卢卢堂堂卢卢卢卢锕卢卢卢卢卢卢卢卢卢卢卢卢卢锕锕锢蚓 => 卢堂卢锕卢锕锢蚓            , gt: b'\xe5\x82\x8d\xe8\xa1\xa2\xe6\x90\x90\xe5\x8e\x89e\xe7\xba\xa\xe7\xa2\xb0\xe8\xb8\x9e\xe6\xb8\x85'
卢卢卢卢卢卢卢懊懊卢卢卢卢懊懊懊卢卢卢卢卢卢锕锕锕蚓 => 卢懊卢懊卢锕蚓             , gt: b'\xe5\xa4\xb8\xe9\x9b\x86\xe6\x9\x8b\xe5\xa8\xb4\xe6\xa9\xb9\xe7\x94\xb1\xe8\x9d\x8\xe9\x82\xb8\xe4\xb\x91'
卢蚓卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢无无无卢狱锕锕锕蚓 => 卢蚓卢无卢狱锕蚓            , gt: b'\xe4\xb\xb\xe7\xb\xa3\xe8\x84\x82\xe8\x8c\xb4\xe7\x85\xa4\xe5\x8a\x9b\xe6\xa4\x8e\xe6\x94\xb9\xe5\x94\x90'
卢代堂堂卢无无无无无无懊懊维捌卢卢卢卢卢卢卢卢锕锕锕 => 卢代堂卢无懊维捌卢锕          , gt: b'\xe8\xbe\x9b\xe6\xb2\xa5\xe7\x89\xa9\xe6\x8a\xb1\xe6\xb7\xb1\xe7\x9b\x8f\xe5\x94\xa4\xe5\x9c\xb\xe6\x81\xb9'
卢代卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢防骄骄骄 => 卢代卢防骄               , gt: b'\xe6\x9c\xbd\xe8\xb4\xb4\xe6\xbc\xb1\xe4\xb\x98\xe5\x8e\x89\xe8\xb0\x93\xe6\xb4\x84\xe5\x87\x87'
卢卢堂堂卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢锕锕锢蚓 => 卢堂卢锕锢蚓              , gt: b'\xe6\x91\x94\xe9\x83\x85\xe7\x9b\x9b\xe5\xb1\x9e\xe7\x9d\x91\xe6\xb\xa1\xe6\x86\x8b\xe6\x9d\x8f\xe7\xa2\xb4'
卢卢堂堂堂踊卢卢卢卢卢懊懊懊懊卢卢卢卢卢卢卢卢锢骄锕 => 卢堂踊卢懊卢锢骄锕           , gt: b'\xe5\xa6\x8\xe6\xb6\x9f\xe8\x8e\x8e\xe5\x86\xac\xe7\x8a\x81\xe6\xad\xa6\xe7\xba\xb0\xe6\x97\xad\xe6\xb6\xa6'
卢卢堂卢卢卢卢卢卢卢卢卢无无无无无卢卢卢卢卢卢锕锕锕 => 卢堂卢无卢锕              , gt: b'\xe8\x85\xbf\xe8\x8\x9c\xe6\x9d\xa0\xe7\x9f\xbd\xe7\xa8\x9e\xe4\xbd\x9a\xe4\xb9\xb1\xe6\x81\x82\xe7\xb\xbf'
卢蚓蚓卢卢卢卢卢卢卢卢卢卢卢卢无卢卢卢卢卢卢卢锕锕蚓 => 卢蚓卢无卢锕蚓             , gt: b'\xe8\xbf\x84\xe7\x85\x85\xe5\xa0\xa\xe5\x86\xa2\xe5\x8d\x8f\xe4\xbc\x9f\xe9\xa9\xb1\xe5\xb\x8a\xe8\x9b\x87'
卢蚓堂卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢卢庇锕锢骄 => 卢蚓堂卢庇锕锢骄            , gt: b'\xe8\xbf\x9f\xe5\x8f\x9f\xe9\xa\x91\xe2\x80\x96\xe6\xbc\x89\xe5\x8c\x95\xe6\x8\xb7\xe8\x8c\xb8\xe8\xa4\xa5'
I know it's the encoding problem,but don't know how to solve it, I have tried many ways but failed.

**Comment by Aurora11111** [comment]
I solved it out! it's because of my datasets is not enough,now I increase the datasets much ,it perform well!

**Comment by ghost** [comment]
Met the same problem.

**Comment by Aurora11111** [comment]
@GYZHikari check your datesets or modify your lr to a small value
