### ISSUE TITLE
CMake Error THC_LIBRARY notfound

### ISSUE THREAD

**Issue by ll36771** [bgshih/crnn#2]
There is an erro when i execute sh build_cpp.sh .THC_LIBRARY NOTFOUND?
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
THC_LIBRARY
    linked by target "crnn" in directory /root/crnn/src/cpp

-- Configuring incomplete, errors occurred!
See also "/root/crnn/src/cpp/build/CMakeFiles/CMakeOutput.log".

I would like to know what is thc_library?where could i get thc_library?

**Comment by ll36771** [comment]
@bgshih

**Comment by bgshih** [comment]
Is your Torch7 installation at ${HOME}/torch ? If not, you may need to change src/cpp/CMakeLists.txt manually.

**Comment by ll36771** [comment]
Thanks a lot.The problem has been solved.There is a new problem.When i train a new model,I  ncountered a new problem.
[03/16/16 15:58:56]  Loading datasets...	
/root/torch/install/bin/luajit: ./DatasetLmdb.lua:19: attempt to index field 'env' (a nil value)
stack traceback:
	./DatasetLmdb.lua:19: in function 'loadDataset'
	./DatasetLmdb.lua:13: in function '__init'
	/root/torch/install/share/lua/5.1/torch/init.lua:91: in function </root/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DatasetLmdb'
	main_train.lua:46: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
Is there anything wrong with my dataset or something else?Thanks!

**Comment by ll36771** [comment]
Thanks a lot.The problem have been solved.
When i train a new model,i encountered a new problem？
[03/16/16 16:16:46]  Loading datasets...	
[03/16/16 16:16:46]  Start training...	
/root/torch/install/bin/luajit: bad argument #3 to '?' (torch.*Tensor expected, got nil)
stack traceback:
	[C]: at 0x7feef0dc9290
	[C]: in function '__newindex'
	./utilities.lua:33: in function 'str2label'
	./DatasetLmdb.lua:81: in function 'allImageLabel'
	./training.lua:84: in function 'trainModel'
	main_train.lua:51: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
Oh,I don't use the cudnn!
@bgshih

**Comment by ll36771** [comment]
Is there anything wrong with my dataset or something else?

**Comment by bgshih** [comment]
The function receives a nil argument. I would suggest debugging it with fb.debugger.

**Comment by wew2012** [comment]
Could you tell me how did you solve THC_LIBRARY NOTFOUND error?

**Comment by bgshih** [comment]
@wew2012 Did you install Torch7 in the home directory (by default it is)? Also, where is your `libTHC.so`? You can find it by `locate libTHC.so`.

**Comment by wew2012** [comment]
Yes, I install Torch7 in `${home}/torch`. But there isn't a gpu in my computer. Does it matter?

**Comment by bgshih** [comment]
@wew2012 I haven't tested it under CPU-only environment. Maybe you can try removing the THC dependencies by removing https://github.com/bgshih/crnn/blob/master/src/cpp/CMakeLists.txt#L20-L21

**Comment by bgshih** [comment]
@wew2012 CRNN should be able to run on CPU, but some modifications are required. Currently, it won't run without a GPU.

**Comment by wew2012** [comment]
Actually, I tried to compile without THC. However, it didn't pass. Is any modifications needed besides the modifications of files in `crnn/src/cpp`? If not too much modifications needed, I want to have a try.

**Comment by bgshih** [comment]
@wew2012 It could require a non-trivial amount of work to make CRNN GPU-free. If you are going to try, I suggest starting from `model/crnn_demo/config.lua`, the `cudnn` should be replaced by `nn`. Then you might have to solve some other issues.

**Comment by wew2012** [comment]
@bgshih All right, I think I'd better give up.

**Comment by zeynali** [comment]
Hi ll36771 ,
i have same problem , [https://github.com/MhLiao/TextBoxes_plusplus/issues/7#issuecomment-364329705](url)
please help me , How do you solved the problem.
