### ISSUE TITLE
Any particular reason for working on Grayscale images? Why not RGB?

### ISSUE THREAD

**Issue by ravikantb** [bgshih/crnn#22]
Hi,

I have made changes in crnn to make it work with RGB images but I am curious to know why did the author write it in a way to work on Grayscale images only? Is it because they achieved more accuracy on Grayscale as compared to RGB images? 
I will be doing some tests to verify it myself, but just wanted to know if anyone here can share their views/experiences about the same.

**Comment by bgshih** [comment]
@ravikantb There should be no problem working on color images. CRNN uses grayscale images because the training images are grayscale (http://www.robots.ox.ac.uk/~vgg/data/text/). Also, as I see, color information is not as important to text as to general scene objects.

**Comment by ravikantb** [comment]
In my tests also, there wasn't much difference when using Grayscale images instead of RGB images. Closing this question as it seems to answer my query. Thanks @bgshih for your input. :)

**Comment by Jayhello** [comment]
@ravikantb   does use this train other language ? can you give the train image and label example?

**Comment by Jayhello** [comment]
@ravikantb 
Can you give me the example of RGB images training? how to change the code?

I am a new coder to lua and do not familer to rnn.
