### ISSUE TITLE
Query - Why is it necessary to have images of fixed width

### ISSUE THREAD

**Issue by mineshmathew** [bgshih/crnn#25]
@bgshih In the paper it is mentioned that images are resized to a height of 32 while width is adjusted by keeping the original aspect ratio. But I see that the code resizes all images to a fixed size 32*100.
`img = Image.scale(img, 100, 32)[1]` in function  _loadAndResizeImage_

Is it necessary to do so when the architecture supports variable length sequences.

**Comment by ravikantb** [comment]
@mineshmathew : I think its not necessary to use the same width height restrictions and depends on the case at hand. Like in my case, having the width of 300 gives me better accuracy. I am going to try some more cases, will report if I find any more improvements. Hope it helps.

**Comment by ahmedmazari-dhatim** [comment]
@mineshmathew , @ravikantb  if l understand, we have to rescale all the images to a fixed size (100,32) or other things . But it's problematic because if we have images of different dimension (97,35) (24,76) , (96,38) how to deal with such a problem ?

**Comment by FrBernkastel** [comment]
@ravikantb @bgshih  But when I want to train the images with different widths in a batch, Tensor cannot accept data with different width. Certainly, it is ok when I set batch_size as 1.
