### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by rremani** [bgshih/crnn#31]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
THPP_LIBRARY
    linked by target "crnn" in directory /home/ce/Documents/crnn/src/cpp

-- Configuring incomplete, errors occurred!
See also "/home/ce/Documents/crnn/src/cpp/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat ‘*.so’: No such file or directory

**Comment by zimenglan-sysu-512** [comment]
@rremani have you solved this problem?

**Comment by rremani** [comment]
No , I stuck at that very point.

**Comment by rremani** [comment]
In a detailed way,
mkdir: cannot create directory ‘build’: File exists
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
THPP_LIBRARY
linked by target "crnn" in directory /home/ce/Documents/crnn/src/cpp

-- Configuring incomplete, errors occurred!
See also "/home/ce/Documents/crnn/src/cpp/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found. Stop.
cp: cannot stat ‘*.so’: No such file or directory

First I installed torch7 from the site then installed fblualib from the commits given in the issue #1 that you posted.
My torch is installed in Home directory (/home/ce/torch) and fblualib(/tmp/fblualib-build.YTz6tN)in temp pasting both the paths, I feel I need to change the Cmakellists.txt of crnn.

CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7 FATAL_ERROR)

PROJECT(crnn)

FIND_PACKAGE(OpenMP)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 ${OpenMP_CXX_FLAGS} -Wall")

# Change this line if your Torch7 is installed elsewhere
SET(TORCH_ROOT "$ENV{HOME}/torch/install")

SET(SEARCH_PATHS
  "/usr/local/lib"
  "${TORCH_ROOT}/lib")

# dependencies
FIND_LIBRARY(THPP_LIBRARY thpp
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(LUAT_LIBRARY luaT
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(TH_LIBRARY TH
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(THC_LIBRARY THC
  PATHS ${SEARCH_PATHS})
SET(EXT_LIBRARIES ${THPP_LIBRARY} ${LUAT_LIBRARY} ${TH_LIBRARY} ${THC_LIBRARY})
SET(EXT_INCLUDE_DIRS "${TORCH_ROOT}/include" "${TORCH_ROOT}/include/TH")

INCLUDE_DIRECTORIES(${EXT_INCLUDE_DIRS})
ADD_LIBRARY(crnn SHARED init.cpp ctc.cpp)
TARGET_LINK_LIBRARIES(crnn ${EXT_LIBRARIES})

Do I need to change the path for Torch and where it is searching the libraries for the below lines.
SET(TORCH_ROOT "$ENV{HOME}/torch/install")
SET(SEARCH_PATHS
"/usr/local/lib"
"${TORCH_ROOT}/lib")

Thanks

**Comment by LavieC** [comment]
I have met some thing similar, like:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUAT_LIBRARY
    linked by target "crnn" in directory /home/CRNN/crnn/src/cpp
THC_LIBRARY
    linked by target "crnn" in directory /home/CRNN/crnn/src/cpp
TH_LIBRARY
    linked by target "crnn" in directory /home/CRNN/crnn/src/cpp
```

Tried locating those library manually. I found that my THPP_LIB is actually in somewhere else rather than ../torchroot/lib,then I changed those search path from
```
SET(SEARCH_PATHS "${TORCH_ROOT}/lib")
FIND_LIBRARY(THPP_LIBRARY thpp
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(LUAT_LIBRARY luaT
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(TH_LIBRARY TH
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(THC_LIBRARY THC
  PATHS ${SEARCH_PATHS})
```
to
```
SET(SEARCH_PATHS "${TORCH_ROOT}/lib")
FIND_LIBRARY(THPP_LIBRARY thpp
  PATHS "usr/local/lib")
FIND_LIBRARY(LUAT_LIBRARY luaT
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(TH_LIBRARY TH
  PATHS ${SEARCH_PATHS})
FIND_LIBRARY(THC_LIBRARY THC
  PATHS ${SEARCH_PATHS})
```
And it all works ! 
P.S. I ran those in this docker image [bethgelab/jupyter-torch](https://hub.docker.com/r/bethgelab/jupyter-torch/).
Wish it helps~

**Comment by rremani** [comment]
Thanks @LavieC Lav , I finally was able to run the demo. The major problem was with the successful installation of fblualib which really irritated me. Now, I have created a docker file built on the docker file you provided me **docker pull rremani/cuda_crnn_torch** . 
Thanks again!

**Comment by qnkhuat** [comment]
@rremani can u help me install thpp ? I'm running ubuntu 16.04

**Comment by rremani** [comment]
@qnkhuat  I can try to help you but it takes lot of time to figure out what the error is actually about. I would suggest you to use docker image rremani/cuda_crnn_torch which has everything installed.
Happy Learning!
