### ISSUE TITLE
can anyone give train image and label for example?

### ISSUE THREAD

**Issue by Jayhello** [bgshih/crnn#35]
hello:
I want to train a new model more word than english?
but I don't how the training image is like and is label  ( example image may like  below )
For char like "你" how many images to prepare? and the size and label?
![image](https://cloud.githubusercontent.com/assets/16144935/22019485/b9f5aa7e-dcee-11e6-864d-55b18ec32a60.png)

![image](https://cloud.githubusercontent.com/assets/16144935/22019497/ca426f5c-dcee-11e6-9d03-3a203f2de4dc.png)

**Comment by haikuoyao** [comment]
Did you figure out it? I'm on the same boat with you

**Comment by lisayan** [comment]
I'm also wondering what the labelList should look like for a set of images.
