### ISSUE TITLE
utilities.lua:253 assertion failed. assert(#state.bnVars == #stateToLoad.bnVars)

### ISSUE THREAD

**Issue by luweishuang** [bgshih/crnn#4]
when I do "th demo.lua", I encountered this error.I  added "print(#state.bnVars)" funding it equals to 3. Also I  "print(#stateToLoad.bnVars)" and  it is 6. I don't know how to do about this error.

**Comment by bgshih** [comment]
Hi, have you tried upgrading your Torch7 to the latest version?

**Comment by luweishuang** [comment]
I tried doing "sh update.sh" in torch folder and "th demo.lua",   encountered the same error just as before

**Comment by luweishuang** [comment]
I have solved this problem, I reinstall torth again and it's ok
