### ISSUE TITLE
Compilation failed, what was the environment for your program? Much thanks

### ISSUE THREAD

**Issue by Suyuanhang** [bgshih/crnn#44]
@bgshih Dear author

As we are trying the reproduce your work, we found that the program is no longer compatible with latest folly, fbthrift, thpp, and fblualib.
Solution in #1 is no longer workable either due to that version is no longer compatible with latest Ubuntu 16.04.

If update your program to the latest thpp, fblualib, folly and fbthrift requires too much effort, can you let us know what was the environment for your program?
The version of: linux (ubuntu 14.04, 15.04, 16.04, etc.?)
                        torch (torch 7?)
                        folly (roughly which time period?)
                        fbthrift (roughly which time period?)
                       thpp (roughly which time period?)
                       fblualib (roughly which time period?)
                        cuda
                        cudnn
                       
Thank you

**Comment by xiequnyi** [comment]
@Suyuanhang ：The correct versions is as follows, and I have try that :
you can take it as a shell file and just run it :
#!/bin/bash
git clone https://github.com/facebook/folly.git
git clone -b v2016.12.12.00 https://github.com/facebook/fbthrift.git
git clone https://github.com/facebook/thpp
git clone https://github.com/facebook/fblualib
cd thpp
git reset --hard ebb4fcbb4a9b3310ac0a36eb37775a45f111448b
cd ..
cd fblualib
git reset --hard bdcf94bb835c41b5d822371fb6f7b75c1d53efbc
cd ..
cd folly
git reset --hard 0fdbb61ecd5679f0cd2bf13f867e9b72212ec371
cd ..

**Comment by xiequnyi** [comment]
@Suyuanhang  cuda 7.5 and cudnn 5 (and later) work!

**Comment by lvpengyuan** [comment]
I use the one-step installation script to install and compile  folly, fbthrift, TH++, and FBLuaLib on my machine.  The demo runs well.
curl -sk https://raw.githubusercontent.com/facebook/fblualib/master/install_all.sh | bash

The environment for this program:
Ubuntu 14.04
Torch7
Cuda 7.5
Cudnn 5 (and later)

**Comment by Suyuanhang** [comment]
@lvpengyuan Thank you for the comments. I can get the code compiled under your system specifications.
BTW, I used gcc 4.8.

**Comment by selcouthlyBlue** [comment]
I got this error in trying to build crnn (after adding the path to the thrift library)

`In file included from /usr/local/include/folly/io/IOBuf.h:32:0,
                 from /usr/local/include/thrift/lib/cpp2/protocol/Protocol.h:25,
                 from /home/kapitan/torch/install/include/thpp/if/gen-cpp2/Tensor_types.h:10,
                 from /home/kapitan/torch/install/include/thpp/Storage.h:22,
                 from /home/kapitan/torch/install/include/thpp/Tensor.h:14,
                 from /home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:8:
/usr/local/include/folly/FBVector.h: In lambda function:
/usr/local/include/folly/FBVector.h:1432:49: error: parameter packs not expanded with ‘...’:
           M_construct(start, std::forward<Args>(args)...);
                                                 ^
/usr/local/include/folly/FBVector.h:1432:49: note:         ‘args’
In file included from /home/kapitan/torch/install/include/thpp/if/gen-cpp2/Tensor_types.h:13:0,
                 from /home/kapitan/torch/install/include/thpp/Storage.h:22,
                 from /home/kapitan/torch/install/include/thpp/Tensor.h:14,
                 from /home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:8:
/usr/local/include/folly/io/Cursor.h: In member function ‘size_t folly::io::detail::CursorBase<Derived, BufType>::cloneAtMost(std::unique_ptr<folly::IOBuf>&, size_t)’:
/usr/local/include/folly/io/Cursor.h:443:13: error: ‘make_unique’ is not a member of ‘std’
       buf = std::make_unique<folly::IOBuf>();
             ^
/usr/local/include/folly/io/Cursor.h:443:13: note: suggested alternative:
In file included from /usr/local/include/thrift/lib/cpp/Thrift.h:23:0,
                 from /usr/local/include/thrift/lib/cpp2/Thrift.h:20,
                 from /home/kapitan/torch/install/include/thpp/if/gen-cpp2/Tensor_types.h:9,
                 from /home/kapitan/torch/install/include/thpp/Storage.h:22,
                 from /home/kapitan/torch/install/include/thpp/Tensor.h:14,
                 from /home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:8:
/usr/local/include/folly/Memory.h:63:1: note:   ‘folly::make_unique’
 make_unique(Args&&...) = delete;
 ^
In file included from /home/kapitan/torch/install/include/thpp/if/gen-cpp2/Tensor_types.h:13:0,
                 from /home/kapitan/torch/install/include/thpp/Storage.h:22,
                 from /home/kapitan/torch/install/include/thpp/Tensor.h:14,
                 from /home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:8:
/usr/local/include/folly/io/Cursor.h:443:42: error: expected primary-expression before ‘>’ token
       buf = std::make_unique<folly::IOBuf>();
                                          ^
/usr/local/include/folly/io/Cursor.h:443:44: error: expected primary-expression before ‘)’ token
       buf = std::make_unique<folly::IOBuf>();
                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::forwardBackward(lua_State*) [with T = float; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<float>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:44:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = float; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:210:24:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:22:76: error: conversion from ‘thpp::TensorBase<float, thpp::Storage<float>, thpp::Tensor<float> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<float> >}’ to non-scalar type ‘const thpp::Tensor<float>’ requested
     const thpp::Tensor<T> input     = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:23:78: error: conversion from ‘thpp::TensorBase<int, thpp::Storage<int>, thpp::Tensor<int> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<int> >}’ to non-scalar type ‘const thpp::Tensor<int>’ requested
     const thpp::Tensor<int> targets = fblualib::luaGetTensorChecked<int>(L, 2);
                                                                              ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:25:76: error: conversion from ‘thpp::TensorBase<float, thpp::Storage<float>, thpp::Tensor<float> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<float> >}’ to non-scalar type ‘thpp::Tensor<float>’ requested
     thpp::Tensor<T> gradInput       = fblualib::luaGetTensorChecked<T>(L, 4);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::naiveDecoding(lua_State*) [with T = float; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<float>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:44:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = float; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:210:24:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:153:73: error: invalid initialization of reference of type ‘const thpp::Tensor<float>&’ from expression of type ‘thpp::TensorBase<float, thpp::Storage<float>, thpp::Tensor<float> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<float> >}’
     const thpp::Tensor<T>& input = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                         ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::forwardBackward(lua_State*) [with T = double; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<double>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:44:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = double; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:211:25:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:22:76: error: conversion from ‘thpp::TensorBase<double, thpp::Storage<double>, thpp::Tensor<double> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<double> >}’ to non-scalar type ‘const thpp::Tensor<double>’ requested
     const thpp::Tensor<T> input     = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:23:78: error: conversion from ‘thpp::TensorBase<int, thpp::Storage<int>, thpp::Tensor<int> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<int> >}’ to non-scalar type ‘const thpp::Tensor<int>’ requested
     const thpp::Tensor<int> targets = fblualib::luaGetTensorChecked<int>(L, 2);
                                                                              ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:25:76: error: conversion from ‘thpp::TensorBase<double, thpp::Storage<double>, thpp::Tensor<double> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<double> >}’ to non-scalar type ‘thpp::Tensor<double>’ requested
     thpp::Tensor<T> gradInput       = fblualib::luaGetTensorChecked<T>(L, 4);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::naiveDecoding(lua_State*) [with T = double; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<double>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:44:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = double; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:211:25:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:153:73: error: invalid initialization of reference of type ‘const thpp::Tensor<double>&’ from expression of type ‘thpp::TensorBase<double, thpp::Storage<double>, thpp::Tensor<double> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<double> >}’
     const thpp::Tensor<T>& input = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                         ^
CMakeFiles/crnn.dir/build.make:86: recipe for target 'CMakeFiles/crnn.dir/ctc.cpp.o' failed
make[2]: *** [CMakeFiles/crnn.dir/ctc.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/crnn.dir/all' failed
make[1]: *** [CMakeFiles/crnn.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat '*.so': No such file or directory`

I used the one line installation script to install the dependcies folly, wangle, fbthrift, thpp, and fblualib:

curl -sk https://raw.githubusercontent.com/facebook/fblualib/master/install_all.sh | bash

The environment for this program:
Ubuntu 16.04
Torch7
Cuda 8
Cudnn 5 (and later)

**Comment by selcouthlyBlue** [comment]
I got this error in building ctc.cpp

```
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::forwardBackward(lua_State*) [with T = float; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<float>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:24:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = float; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:210:24:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:22:76: error: conversion from ‘thpp::TensorBase<float, thpp::Storage<float>, thpp::Tensor<float> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<float> >}’ to non-scalar type ‘const thpp::Tensor<float>’ requested
     const thpp::Tensor<T> input     = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:23:78: error: conversion from ‘thpp::TensorBase<int, thpp::Storage<int>, thpp::Tensor<int> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<int> >}’ to non-scalar type ‘const thpp::Tensor<int>’ requested
     const thpp::Tensor<int> targets = fblualib::luaGetTensorChecked<int>(L, 2);
                                                                              ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:25:76: error: conversion from ‘thpp::TensorBase<float, thpp::Storage<float>, thpp::Tensor<float> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<float> >}’ to non-scalar type ‘thpp::Tensor<float>’ requested
     thpp::Tensor<T> gradInput       = fblualib::luaGetTensorChecked<T>(L, 4);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::naiveDecoding(lua_State*) [with T = float; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<float>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:24:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = float; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:210:24:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:153:73: error: invalid initialization of reference of type ‘const thpp::Tensor<float>&’ from expression of type ‘thpp::TensorBase<float, thpp::Storage<float>, thpp::Tensor<float> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<float> >}’
     const thpp::Tensor<T>& input = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                         ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::forwardBackward(lua_State*) [with T = double; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<double>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:24:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = double; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:211:25:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:22:76: error: conversion from ‘thpp::TensorBase<double, thpp::Storage<double>, thpp::Tensor<double> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<double> >}’ to non-scalar type ‘const thpp::Tensor<double>’ requested
     const thpp::Tensor<T> input     = fblualib::luaGetTensorChecked<T>(L, 1);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:23:78: error: conversion from ‘thpp::TensorBase<int, thpp::Storage<int>, thpp::Tensor<int> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<int> >}’ to non-scalar type ‘const thpp::Tensor<int>’ requested
     const thpp::Tensor<int> targets = fblualib::luaGetTensorChecked<int>(L, 2);
                                                                              ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:25:76: error: conversion from ‘thpp::TensorBase<double, thpp::Storage<double>, thpp::Tensor<double> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<double> >}’ to non-scalar type ‘thpp::Tensor<double>’ requested
     thpp::Tensor<T> gradInput       = fblualib::luaGetTensorChecked<T>(L, 4);
                                                                            ^
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp: In instantiation of ‘int {anonymous}::naiveDecoding(lua_State*) [with T = double; lua_State = lua_State]’:
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:194:16:   required from ‘const luaL_Reg {anonymous}::Registerer<double>::functions_ [3]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:203:24:   required from ‘static void {anonymous}::Registerer<T>::registerFunctions(lua_State*) [with T = double; lua_State = lua_State]’
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:211:25:   required from here
/home/kapitan/Desktop/Jerome/crnn/src/cpp/ctc.cpp:153:73: error: invalid initialization of reference of type ‘const thpp::Tensor<double>&’ from expression of type ‘thpp::TensorBase<double, thpp::Storage<double>, thpp::Tensor<double> >::Ptr {aka thpp::TensorPtr<thpp::Tensor<double> >}’
     const thpp::Tensor<T>& input = fblualib::luaGetTensorChecked<T>(L, 1);
```

I used the one line installation script to install the dependcies folly, wangle, fbthrift, thpp, and fblualib:

curl -sk https://raw.githubusercontent.com/facebook/fblualib/master/install_all.sh | bash

The environment for this program:
Ubuntu 16.04
Torch7
Cuda 8
Cudnn 5 (and later)

**Comment by Suyuanhang** [comment]
@selcouthlyBlue 
Use Ubuntu 14.04 instead of 16.04, I used cuda 7.5, not sure if cuda 8.0 works.

**Comment by Hidayat786** [comment]
Using the above one step installation
curl -sk https://raw.githubusercontent.com/facebook/fblualib/master/install_all.sh | bash
i got error in the thpp installation in TensorSerialization.cpp.o 
any help ?
i am using ubuntu 14.04 and Cuda 7.5
