### ISSUE TITLE
fblualib version

### ISSUE THREAD

**Issue by githubharald** [bgshih/crnn#45]
Hello,

thanks for sharing CRNN!
Unfortunately installing fblualib is a bit of a pain. We're trying to install it on Ubuntu 14.04. 
Could you tell me which version of fblualib and dependencies (folly, wangle, thrift, thpp) you are using? I think using exactly the same versions as you did would be the easiest way to get everything running.

Thanks in advance
Harald

**Comment by githubharald** [comment]
ok we finally got it working. CRNN gives nice results.

**Comment by heildever** [comment]
Hi, could you please give me hints. Which way you have followed to build the project ? Even the Docker seems bit problematic.

**Comment by githubharald** [comment]
the main problem was that the install_all.sh from fblualib didn't work. We just went step by step through this script and manually installed everything. Take care to checkout the correct versions of the dependencies.

**Comment by heildever** [comment]
Instead I have pulled @rremani's docker image, he did a great job by gathering everything together.

**Comment by heildever** [comment]
Hi, were you able to run the net with a lexicon ?

**Comment by githubharald** [comment]
never tried it.
I've just used best path decoding.

**Comment by qnkhuat** [comment]
Hi @githubharald , what os u are running?

**Comment by githubharald** [comment]
we used 14.04, see first post.

**Comment by qnkhuat** [comment]
do u know is it works on 16.04 ?

**Comment by githubharald** [comment]
never tried it with 16.04.
