### ISSUE TITLE
What version of this program does it work with?(32bit or 64bit)

### ISSUE THREAD

**Issue by mskim1024** [bgshih/crnn#52]
I am trying to use Unicode to learn more than 10,000 characters, but I still get an error message saying that the memory is insufficient. I tracked memory usage so I could see that it stopped at 3.3G. Does this program only work on 32bit? Or did I make a mistake?

**Comment by bgshih** [comment]
@mskim1024 Torch7 libraries are 64bit. But its interpreter LuaJIT is [32bit-only](http://stackoverflow.com/questions/35155444/why-is-luajits-memory-limited-to-1-2-gb-on-64-bit-platforms), which is very likely to be the reason of your memory problem. Make sure you are not storing large arrays in LuaJIT tables. Instead, try to put such an array into a Torch7 tensor.

**Comment by mskim1024** [comment]
Thank you for your quick and kind reply. It has helped a lot.
