### ISSUE TITLE
The issue of creating a dataset with create_dataset.py with python3.5

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [bgshih/crnn#53]
Hello,
l'm trying to create my own dataset to train my model from scratch. I'm working with python3.5.2 .While l'm creating a dataset l encountered the following problems.
1)

```
with open(imagePath, 'r') as f:
     imageBin = f.read()
```

returns the following error :

```
codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

l fixed it as follow :
```

with open(imagePath, 'rb') as f:
       imageBin = f.read()

```
2)for python3

`for i in xrange(nSamples): `should be replaced by `for i in range(nSamples):`
and
`for k, v in cache.iteritems(): `should be replaced by` for k, v in cache.items():`

    However, l got the following error at this line :

`txn.put(k, v) `in  `def writeCache(env, cache): `function

```
line 86, in createDataset
   writeCache(env, cache)
 File "/home/ahmed/Downloads/crnn.pytorch-master/data-processing.py", line 46, in writeCache
   txn.put(k, v)
TypeError: Won't implicitly convert Unicode to bytes; use .encode()

```
Here is my whole code :

```
import os
import lmdb # install lmdb by "pip install lmdb"
import cv2
import numpy as np
import glob

real_path='/home/ahmed/Downloads/sample/train/'
path='/home/ahmed/Downloads/sample/'
path_train='train/'

path_output='/home/ahmed/Downloads/sample/output/'



os.chdir(path+path_train)
images_train = glob.glob("*.jpg")
left_train,labels_train,right_train = list(zip(*[os.path.splitext(x)[0].split('_')
                                         for x in images_train]))



def checkImageIsValid(imageBin):
    if imageBin is None:
        return False
    imageBuf = np.fromstring(imageBin, dtype=np.uint8)
    img = cv2.imdecode(imageBuf, cv2.IMREAD_GRAYSCALE)
    imgH, imgW = img.shape[0], img.shape[1]
    if imgH * imgW == 0:
        return False
    return True


def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            txn.put(k, v)


def createDataset(outputPath,images_train, labels_train, lexiconList=None, checkValid=True):
    """
    Create LMDB dataset for CRNN training.
    ARGS:
        outputPath    : LMDB output path
        imagePathList : list of image path
        labelList     : list of corresponding groundtruth texts
        lexiconList   : (optional) list of lexicon lists
        checkValid    : if true, check the validity of every image
    """
    assert(len(images_train) == len(labels_train))
    nSamples = len(images_train)

    env = lmdb.open(path_output, map_size=1099511627776)
    cache = {}
    cnt = 1
    for i in range(nSamples):
        imagePath = images_train[i]
        label = labels_train[i]
        if not os.path.exists(real_path+imagePath):
            print('%s does not exist' % imagePath)
            continue
        with open(real_path+imagePath, 'rb') as f:
            imageBin = f.read()
        if checkValid:
            if not checkImageIsValid(imageBin):
                print('%s is not a valid image' % imagePath)
                continue

        imageKey = 'image-%09d' % cnt
        labelKey = 'label-%09d' % cnt
        cache[imageKey] = imageBin
        cache[labelKey] = label
        if lexiconList:
            lexiconKey = 'lexicon-%09d' % cnt
            cache[lexiconKey] = ' '.join(lexiconList[i])
        if cnt % 1000 == 0:
            writeCache(env, cache)
            cache = {}
            print('Written %d / %d' % (cnt, nSamples))
        cnt += 1
    nSamples = cnt-1
    cache['num-samples'] = str(nSamples)
    writeCache(env, cache)
    print('Created dataset with %d samples' % nSamples)


if __name__ == '__main__':
    createDataset(path_output,images_train, labels_train)

```

what's wrong with 

`txn.put(k, v) ` in  `def writeCache(env, cache): ` function

```

line 86, in createDataset
   writeCache(env, cache)
 File "/home/ahmed/Downloads/crnn.pytorch-master/data-processing.py", line 46, in writeCache
   txn.put(k, v)
TypeError: Won't implicitly convert Unicode to bytes; use .encode()
```

**Comment by hellbago** [comment]
Have you fixed this issue? @ahmedmazari-dhatim

**Comment by ahmedmazari-dhatim** [comment]
Hi @hellbago ,

if you are using python 2 then :  
```
def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.iteritems():
            txn.put(k, v)
```

if you are using python3

```
def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            txn.put(k.encode())
            txn.put(v)

```
Let me know if it works

**Comment by hellbago** [comment]
it works in pyhton 2, but in python 3 i get the same error @ahmedmazari-dhatim

**Comment by ahmedmazari-dhatim** [comment]
```
def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            txn.put(k.encode())
         
```
remove  `txn.put(v)`

**Comment by angel1288** [comment]
@ahmedmazari-dhatim  @hellbago  Hello！When I use _data.mdb_ to train, I get the error:

![wk_yok6yo ngned64b _85q](https://user-images.githubusercontent.com/20549473/34404445-88d9e37e-ebe8-11e7-8048-2d1fef261831.png)

 When creating a dataset with _create_dataset.py_, _imageBin = f.read()_ is unintelligible text. Does it lead to the above error? Thank you!

**Comment by neutronest** [comment]
Maybe it's useful to upgrade py2 style to py3, such as 'iteritem' for dict

**Comment by kai-kaushik** [comment]
@ahmedmazari-dhatim how is that a solution? If we remove v, The created dataset wont have that part of the data itself

**Comment by pczzy** [comment]
txn.put(str(k).encode(), str(v).encode())
that will works for python3

**Comment by Aurora11111** [comment]
**in python2.x:**
**Line 21:**    def writeCache(env, cache):
                       with env.begin(write=True) as txn:
                        for k, v in cache.iteritems():
                             txn.put(k, v)

**Line 51:**    with open(imagePath, 'r') as f:
                        imageBin = f.read()
****

**Comment by hzli-ucas** [comment]
In python3, the text (str) and bytes can no longer be used in the same way. The function txn.put(...) takes bytes as input, so the unicode string must be explicitly encoded to bytes first.

> txn.put(str(k).encode(), str(v).encode())
> that will works for python3

Yes this works for python3, but there'll be some troubles trying to read image data from the generated lmdb file. Because there are actually two types of values in the dict "cache", including cache['label-XXX'] of type "str" and cache['image-XXX'] of type "bytes". The codes above are fine for cache['label-XXX']. Meanwhile, the cache['image-XXX'] **b'\xff\xd8\xff\xe0...'** will be encoded to be **b'b\'\\xff\\xd8\\xff\\xe0...\''**. We can decide whether to encode the value by its type, as follows

```
def writeCache(env, cache):
    with env.begin(write=True) as txn:
        for k, v in cache.items():
            if type(v) == str:
                v = v.encode()
            txn.put(k.encode(), v)
```

**Comment by SuperIRabbit** [comment]
> In python3, the text (str) and bytes can no longer be used in the same way. The function txn.put(...) takes bytes as input, so the unicode string must be explicitly encoded to bytes first.
> 
> > txn.put(str(k).encode(), str(v).encode())
> > that will works for python3
> 
> Yes this works for python3, but there'll be some troubles trying to read image data from the generated lmdb file. Because there are actually two types of values in the dict "cache", including cache['label-XXX'] of type "str" and cache['image-XXX'] of type "bytes". The codes above are fine for cache['label-XXX']. Meanwhile, the cache['image-XXX'] **b'\xff\xd8\xff\xe0...'** will be encoded to be **b'b'\xff\xd8\xff\xe0...''**. We can decide whether to encode the value by its type, as follows
> 
> ```
> def writeCache(env, cache):
>     with env.begin(write=True) as txn:
>         for k, v in cache.items():
>             if type(v) == str:
>                 v = v.encode()
>             txn.put(k.encode(), v)
> ```

This is the real solution if we don't change the reading code. Thanks!

**Comment by garspace** [comment]
> txn.put(str(k).encode(), str(v).encode())
> that will works for python3

this works for me

**Comment by garspace** [comment]
> In python3, the text (str) and bytes can no longer be used in the same way. The function txn.put(...) takes bytes as input, so the unicode string must be explicitly encoded to bytes first.
> 
> > txn.put(str(k).encode(), str(v).encode())
> > that will works for python3
> 
> Yes this works for python3, but there'll be some troubles trying to read image data from the generated lmdb file. Because there are actually two types of values in the dict "cache", including cache['label-XXX'] of type "str" and cache['image-XXX'] of type "bytes". The codes above are fine for cache['label-XXX']. Meanwhile, the cache['image-XXX'] **b'\xff\xd8\xff\xe0...'** will be encoded to be **b'b'\xff\xd8\xff\xe0...''**. We can decide whether to encode the value by its type, as follows
> 
> ```
> def writeCache(env, cache):
>     with env.begin(write=True) as txn:
>         for k, v in cache.items():
>             if type(v) == str:
>                 v = v.encode()
>             txn.put(k.encode(), v)
> ```

thanks ,this code is corrected for my work in python3
