### ISSUE TITLE
If the model works for variable length images, why we need to rescale images to a fixed size such  as (100,32) ?

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [bgshih/crnn#54]

**Comment by misssprite** [comment]
IMHO, nearly all models take fixed size input if you use a scalar loss.
The "variable length image" in the paper means in test time, I think.

**Comment by ahmedmazari-dhatim** [comment]
@misssprite , yes in the test time it takes images of variable length, but if you dive into the code, you find out that even test images are rescaled to (100,32)

**Comment by misssprite** [comment]
@ahmedmazari-dhatim You may try with scaling to other widths, as long as the height is fixed to 32.
