### ISSUE TITLE
How do you explain that network predicts blank firsr  “ --hh-e-l-ll-oo-- ”?

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [bgshih/crnn#57]
Hello,

1) l noticed that  all the predicted sequences start with a blank . However, all the sequences start with a character. 

2) “--hh-e-l-ll-oo--” is mapped into "hello"  : 
what does it mean by     "-ll-" 
is it the fact that the network predicts two characters in the same frame ?
if yes , l'm wondering if it predicts two different characters for the same frame let's say '-lm-' how  it can choose between l and m 

Thank you

**Comment by misssprite** [comment]
2.No. "-ll-" means there are two successive frames both produce "l". A path like "--hh-e-l-ll-oo--" is mapped to a sequence "hello" through ctc. You can refer to the paper by Graves.

**Comment by githubharald** [comment]
for each frame of the image, a prediction for a label is done, which results in a path like “--hh-e-l-ll-oo--”.
The CTC layer includes a step which takes those paths and removes all repeated labels and all blanks. Just look at your example and first remove repeated labels (-> “--h-e-l-l-o--”) and then blanks (-> “hello”).
More details can be found in the original paper, in which this function is just called B.
