### ISSUE TITLE
model:add(cudnn.SpatialMaxPooling(2, 2, 1, 2, 1, 0))?

### ISSUE THREAD

**Issue by ll36771** [bgshih/crnn#6]
It is mentioned that "In the 3rd and the 4th maxpooling layers, we adopt 1 × 2 sized rectangular pooling
windows instead of the conventional squared ones" in your paper.Should I change model:add(cudnn.SpatialMaxPooling(2, 2, 1, 2, 1, 0)) to model:add(cudnn.SpatialMaxPooling(1, 2, 1, 2, 1, 0)).Could it make better?

**Comment by bgshih** [comment]
@ll36771 It's a typo in the paper :) Should be "1 x 2 stride sizes". Please keep using the parameter settings in the code.
