### ISSUE TITLE
Quick question about crnn_demo_model.t7

### ISSUE THREAD

**Issue by michael-chiang-mc5** [bgshih/crnn#62]
Hi @bgshih 

Thank you for including working code for CRNN. It makes trying out your software a lot easier.

I was wondering if you could clarify: 
Would crnn_demo_model.t7 produce about the same result for **lexicon-free word recognition on the SVT dataset** as the model you used in your paper http://arxiv.org/abs/1507.05717? (80.8% on the SVT dataset)?

Based on https://github.com/bgshih/crnn/issues/33, I expect it would but I wanted to make sure.

Thank you,
Michael

**Comment by bgshih** [comment]
@michael-chiang-mc5 As the code has been modified a bit since the publication of the paper, it should be able to reproduce a close result, if not the same.

**Comment by michael-chiang-mc5** [comment]
Alright, thank you for your quick reply!
