### ISSUE TITLE
some errors in create_dataset.py

### ISSUE THREAD

**Issue by chengzhanzhan** [bgshih/crnn#8]
There are some typos in create_dataset.py.

line 60:
it should be "if cnt % 1000 == 0"

line 66:
When I run the code in ubuntu 14.04, I get the error as follows:

Traceback (most recent call last):
  File "create_dataset.py", line 83, in <module>
    createDataset(outPath, imagePathList, labelList)
  File "create_dataset.py", line 67, in createDataset
    writeCache(env, cache)
  File "create_dataset.py", line 21, in writeCache
    txn.put(k, v)
TypeError: expected a readable buffer object

I think that line 66 should be revised to " cache['num-samples'] = str(nSamples)", then the code works.

**Comment by bgshih** [comment]
@chengzhanzhan  I've got them fixed. Thank you!
