### ISSUE TITLE
can you or anyone upload all the dependence (folly, thpp fbthrift fblualib)zip file ?

### ISSUE THREAD

**Issue by Jayhello** [bgshih/crnn#98]
can you or anyone upload all the dependence (folly, thpp fbthrift fblualib)zip file ?

There are lots of version of the above package which may conflict with each others?

So anyone who has complied successfully, can upload the zip file ?

**Comment by qnkhuat** [comment]
anyone ??

**Comment by Jayhello** [comment]
I have found, you should't use ubuntu16, but ubuntu14 can compile.
Or use ubuntu16 with docker(install ubuntu14 env)

**Comment by qnkhuat** [comment]
thank u

**Comment by qnkhuat** [comment]
Oh. May I ask can i install ubuntu14 env on a serve running 16.04?

**Comment by loralyc** [comment]
@Jayhello  hello,have you success compile the fbthrift ,I have encountered some problems，could you give me some suggestion? thanks.

`/home/hey/torch/fblualib/folly/_build/include/folly/functional/ApplyTuple.h:45:40: error: ‘remove_reference_t’ is not a member of ‘std’
   using seq = index_sequence_for_tuple<std::remove_reference_t<T>>;
                                        ^
/home/hey/torch/fblualib/folly/_build/include/folly/functional/ApplyTuple.h:45:40: error: ‘remove_reference_t’ is not a member of ‘std’
/home/hey/torch/fblualib/folly/_build/include/folly/functional/ApplyTuple.h:45:64: error: template argument 1 is invalid
   using seq = index_sequence_for_tuple<std::remove_reference_t<T>>;
`
